language: generic
services: docker
dist: xenial

env:
  global:
  - REPO_DIR=sisl
  - BUILD_COMMIT=v0.10.0
  - BUILD_DEPENDS=
  - TEST_DEPENDS=

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.9
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.9
        - PLAT=i686
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_PYTHON_OSX_VER=10.6
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.8
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.9
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=pypy-5.7

before_install:
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- clean_code $REPO_DIR $BUILD_COMMIT
- build_wheel $REPO_DIR $PLAT
- ls -l $PWD/$WHEEL_SDIR/*.whl
script:
- install_run $PLAT

deploy:
  provider: releases
  api_key:
    secure: UHu+kC0MlBoT5cxz8N5W1VhgBAbbu/jrZTO55dElrb8AFt3a72B+WL0aML6HBrficdT7FCIhZgUrPBbyeK5sHoLl0ce5QMZ1PDuOR1VSOeBQXVCgTs/wEqe42xQZeoOH+N4s3v8QmWrHjQ2kxjtsY3Ce9Areap4dnld1GxjwXH4PcOXmQVq70yk7tIuMhNgb8VgZuLC1JGxNREtfDn0XZIjg2A7eiXvg/jkkOOM+JuyuI2EUy78Uli1zhLytzZfkFC+O3ZxOWgNuam9d0pRb/iOCJNYQw4FgTIjM4OoaZi5DPqKAhgXhJYBwtz/LqPVdVU7lEvXkNLJ3Ubo8V0+pxNyRUqwuSvn4UUrC7+0GWWTi8tYi37IfvtbLK655L+Nbc4WyGxn3L2O/1Ioz1rH5NryFcFKVw1NoTnC378oKrA49KSdchHhtChWo03YIQZDaVrw11k/+78iL7zPsRovSSv+sK9obzfTWdBmnm+ReP+hP49VwLLtN1m0PtTRLn3S0aHkyYPOA4+MYzVkUwivtQrT5YaYY3I4y7Vw2XgpRXQ5hPw98YilFj33YlkzKWJEO4i8EYvIv5d2jWOM8UQLf0l9FJvfsKdpw8DCXRqc8zBVAUxTrTaIdw0jubR8O8Z8YC4qolxtfM8+YJmqV7f76LOp5yMkipxV27hiK+911s7o=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/${WHEEL_SDIR}/*.whl"
  on:
    repo: zerothi/sisl-wheels
    tags: true
  skip_cleanup: 'true'
